/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavigationMenu from "../NavigationMenu/NavigationMenu";
import Logo from "../Logo/Logo";

const Header: React.FC = () => (
  <header className="flex flex-col justify-center items-center px-96 bg-white min-h-[90px] max-md:px-5">
    <div className="flex-1 py-2.5 max-w-full w-[1140px] max-md:pl-5">
      <div className="flex gap-5 max-md:flex-col">
        <nav className="flex flex-col w-[81%] max-md:ml-0 max-md:w-full">
          <NavigationMenu />
        </nav>
        <div className="flex flex-col ml-5 w-[19%] max-md:ml-0 max-md:w-full">
          <Logo />
        </div>
      </div>
    </div>
  </header>
);

export default Header;
