/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureCard from "./FeatureCard";

const featureData = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/31823f99b83663f07b239f8fa6af938a3d4995a077f53de78bbf3ee6f9d72efd?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856",
    title: "קידום ברשתות החברתיות בעזרת בינה מלאוכתית",
    description:
      "קידום ברשתות החברתיות הוא כלי עוצמתי וחדשני שיכול להביא לתוצאות עצומות. אם זאת יש לזכור קידום מוצרים ושירותים צריך להיעשות בצורה אתית והוגנת",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/bb0dbeedd37edcfa0326eda1390413060de8028fde4ecac4f7b8e7ef43ae23d8?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856",
    title: "2023",
    description:
      "קידום אורגני במנועי חיפוש - עדיין הדרך הטובה ביותר לקדם אתר. יש להקפיד על תוכן איכותי וייחודי, קישורים פנימיים וחיצוניים איכותיים, מהירות טעינה מהירה של האתר ונגישות למכשירים ניידים",
  },
];

const FeatureCards: React.FC = () => {
  return (
    <section className="flex flex-col justify-center items-center px-96 w-full max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap flex-1 justify-center px-44 py-2.5 max-w-full h-full w-[1140px] max-md:px-5">
        {featureData.map((feature, index) => (
          <FeatureCard
            key={index}
            imageSrc={feature.imageSrc}
            title={feature.title}
            description={feature.description}
          />
        ))}
      </div>
    </section>
  );
};

export default FeatureCards;
