/**
 * This code was generated by Builder.io.
 */
import React from "react";

const footerSections = [
  {
    title: "בניית אתרים",
    items: [
      "בניית אתרים",
      "בניית אתר תדמית",
      "בניית אתר מסחר",
      "בניית אתר פורטל",
    ],
  },
  {
    title: "עיצוב אתרים",
    items: ["עיצוב אתרים", "UI/UX", "עיצוב ממשק משתמש", "עיצוב אפליקציות"],
  },
  {
    title: "קידום אתרים ודיגיטל",
    items: ["Facebook", "Instagram", "Tik Tok"],
  },
];

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col w-full max-md:max-w-full">
      <div className="flex flex-col justify-center px-96 w-full bg-fuchsia-950 max-w-[1920px] max-md:px-5 max-md:max-w-full">
        <div className="flex flex-wrap flex-1 justify-center px-16 pt-24 pb-12 size-full max-md:px-5 max-md:max-w-full">
          {footerSections.map((section, index) => (
            <div
              key={index}
              className="flex flex-col grow shrink items-end px-5 text-right min-w-[240px] w-[253px]"
            >
              <h3 className="flex flex-col justify-center w-full text-lg font-semibold leading-tight text-yellow-500 max-w-[285px]">
                <div className="flex flex-col flex-1 w-full">
                  <div className="pb-px w-full">{section.title}</div>
                </div>
              </h3>
              <nav className="flex flex-col justify-center mt-1 max-w-full text-base leading-loose text-gray-200 w-[155px]">
                <ul className="flex flex-col flex-1 w-full">
                  {section.items.map((item, itemIndex) => (
                    <li
                      key={itemIndex}
                      className="flex justify-center items-center pb-1.5 w-full"
                    >
                      <a
                        href="#"
                        className="flex flex-1 shrink items-center self-stretch pl-20 my-auto w-full basis-0"
                      >
                        <span className="self-stretch pb-px my-auto">
                          {item}
                        </span>
                      </a>
                    </li>
                  ))}
                </ul>
              </nav>
            </div>
          ))}
          <div className="flex flex-col grow shrink items-start pl-5 w-[127px]">
            <div className="flex flex-col justify-center max-w-full w-[139px]">
              <div className="flex flex-col flex-1 w-full">
                <div className="flex flex-col w-full">
                  <div className="flex justify-center items-center w-full">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/ba9c948f0cffbbd4d4fbc2a25143ef6db969d17328f40e98372d2c35df01f82f?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856"
                      className="object-contain self-stretch my-auto aspect-[1.51] max-w-[139px] w-[139px]"
                      alt="Footer logo"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col justify-center items-center px-96 pt-px w-full text-sm leading-5 text-center text-white border-t border-solid bg-fuchsia-950 border-t-slate-400 border-t-opacity-20 max-w-[1920px] max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col flex-1 justify-center py-12 w-full">
          <div className="flex flex-col justify-center w-full max-w-[1140px] max-md:max-w-full">
            <div className="flex flex-col flex-1 w-full max-md:max-w-full">
              <div className="pl-96 w-full pr-[572px] max-md:px-5 max-md:max-w-full">
                © {new Date().getFullYear()} | כל הזכויות שמורות
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
