/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";

const Header: React.FC = () => {
  return (
    <header className="flex absolute top-0 right-0 z-0 flex-col justify-center items-center px-96 bg-white min-h-[90px] w-[1920px] max-md:px-5 max-md:max-w-full">
      <div className="flex-1 py-2.5 max-w-full w-[1140px] max-md:pl-5">
        <div className="flex gap-5 max-md:flex-col">
          <Navigation />
          <Logo />
        </div>
      </div>
    </header>
  );
};

export default Header;
