/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo: React.FC = () => {
  return (
    <div className="flex flex-col ml-5 w-[19%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow justify-center min-h-[80px] max-md:mt-10">
        <div className="flex flex-col flex-1 w-full">
          <div className="flex flex-col w-full">
            <div className="flex justify-center items-center w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/7e91ab3b0ddc25f26fadfd8693e0bfc163fe98621b45e54ddafd0d19727a193b?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856"
                className="object-contain self-stretch my-auto aspect-[1.5] max-w-[120px] w-[120px]"
                alt="Company Logo"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Logo;
