/**
 * This code was generated by Builder.io.
 */
import React from "react";

const navigationItems = [
  { label: "דף הבית", href: "#" },
  { label: "אודותינו", href: "#" },
  { label: "תיק עבודות", href: "#" },
  { label: "הדרך שלנו", href: "#" },
  { label: "צרו קשר", href: "#" },
];

const Navigation: React.FC = () => {
  return (
    <nav className="flex flex-col w-[81%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col justify-center self-stretch my-auto text-base font-bold leading-none text-right text-yellow-500 max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col flex-1 w-full max-md:max-w-full">
          <div className="flex justify-center w-full max-md:max-w-full">
            <div className="flex flex-wrap justify-center h-full min-w-[240px] max-md:max-w-full">
              {navigationItems.map((item, index) => (
                <div key={index} className="flex justify-center h-full">
                  <a
                    href={item.href}
                    className="self-stretch px-5 pt-3.5 pb-3.5 h-full"
                  >
                    {item.label}
                  </a>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navigation;
