/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ContactFormProps {}

const ContactForm: React.FC<ContactFormProps> = () => {
  return (
    <form className="flex flex-col justify-center mt-5 text-base text-right text-white max-md:max-w-full">
      <div className="flex flex-col flex-1 px-6 pt-8 pb-8 w-full bg-gray-900 rounded-xl shadow-sm max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col w-full">
          <div className="flex">
            <div className="flex flex-col flex-1 justify-center pb-4 min-h-[61px]">
              <div className="flex flex-wrap justify-center items-center px-2 w-full min-h-[45px]">
                <label htmlFor="phone" className="sr-only">
                  טלפון
                </label>
                <input
                  type="tel"
                  id="phone"
                  className="flex flex-col flex-1 shrink justify-center items-start self-stretch px-7 py-3.5 my-auto w-full bg-gray-900 rounded-sm border-b border-solid basis-0 border-b-yellow-500 max-w-[195px] min-h-[40px] max-md:pl-5
                   focus-visible:outline-none focus-visible:border-yellow-800"
                  placeholder="טלפון *"
                  required
                />
              </div>
            </div>
            <div className="flex flex-col flex-1 justify-center pb-4 min-h-[61px]">
              <div className="flex flex-wrap justify-center items-center px-2 w-full min-h-[45px]">
                <label htmlFor="fullName" className="sr-only">
                  שם מלא
                </label>
                <input
                  type="text"
                  id="fullName"
                  className="flex flex-col flex-1 shrink self-stretch px-3 pt-3 pb-3.5 my-auto w-full bg-gray-900 rounded-sm border-b border-solid basis-0 border-b-yellow-500 max-w-[195px] min-h-[40px]
                   focus-visible:outline-none focus-visible:border-yellow-800"
                  placeholder="שם מלא *"
                  required
                />
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center self-end pb-4 max-w-full min-h-[61px] w-[195px]">
            <div className="flex flex-wrap justify-center items-center px-2 w-full min-h-[45px]">
              <label htmlFor="email" className="sr-only">
                כתובת מייל
              </label>
              <input
                type="email"
                id="email"
                className="flex flex-col flex-1 shrink self-stretch px-3 pt-3 pb-3.5 my-auto w-full bg-gray-900 rounded-sm border-b border-solid basis-0 border-b-yellow-500 max-w-[195px] min-h-[40px]
                 focus-visible:outline-none focus-visible:border-yellow-800"
                placeholder="כתובת מייל *"
                required
              />
            </div>
          </div>
          <div className="flex flex-col justify-center pb-4 w-full font-medium leading-none text-center text-yellow-500 min-h-[61px]">
            <div className="flex flex-wrap items-end pr-64 pl-2 w-full min-h-[45px] max-md:pr-5">
              <button
                type="submit"
                className="flex flex-col grow shrink justify-center p-4 bg-gray-900 border border-yellow-500 border-solid min-h-[40px] w-[104px] hover:border-white hover:text-white"
              >
                <span className="flex justify-center items-center pr-1.5 text-xs w-full">
                  <span>צור פניה חדשה</span>
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  );
};

export default ContactForm;
