/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceCard from "./ServiceCard";

interface Service {
  imageSrc: string;
  title: string;
  description: string;
}

const services: Service[] = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/2dc11235803c60754d3887201f0ab8232d0b90cf0da90e7c08667ba58b98578f?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856",
    title: "בניית אתרים",
    description:
      "בניית אתרים בהתאמה אישית תוך שימוש בטכנולוגיות המתקדמות ביותר וליווי אישי לאורך כל תהליכי הפיתוח",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/212113ed0837e65076c19fddd05e1e668465c3dfb35378ff02eb6953269ec211?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856",
    title: "פיתוח אפליקציות",
    description:
      "פיתוח אפליקציות למובייל. אפליקציות שמשתמשים מבינים בעלות ממשק משתמש מדהים ונוח לשימוש",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/fbd372bb872408aa31c1cbed005d2c9826d4ac57ad4e8dab7fe4d551aebdac5c?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856",
    title: "UX/UI",
    description:
      "עיצוב ממשק משתמש לאתרים ואפליקציות תוך מתן דגש עיקרי וללא פשרות על חווית משתמש מירבית",
  },
];

const ServiceCards: React.FC = () => {
  return (
    <section className="flex flex-col justify-center items-center px-96 w-full max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap flex-1 justify-center py-2.5 max-w-full h-full w-[1140px]">
        {services.map((service, index) => (
          <ServiceCard
            key={index}
            imageSrc={service.imageSrc}
            title={service.title}
            description={service.description}
          />
        ))}
      </div>
    </section>
  );
};

export default ServiceCards;
