/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../components/Layout";
import HeroSection from "../components/HeroSection";
import ServiceSection from "../components/ServiceSection";
import ContactForm from "../components/ContactForm";

const HomePage: React.FC = () => {
  return (
    <Layout>
      <HeroSection />
      <ServiceSection />
      <ContactForm />
    </Layout>
  );
};

export default HomePage;
