/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ContactForm: React.FC = () => {
  return (
    <section className="flex justify-center py-12 w-full px-[480px] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col flex-1 shrink justify-center items-center p-2.5 w-full basis-0 min-w-[240px] max-md:max-w-full">
        <div className="flex flex-col justify-center w-full max-w-[960px] max-md:max-w-full">
          <form className="flex flex-col flex-1 px-6 pt-8 pb-8 w-full bg-white rounded-xl shadow-sm max-md:px-5 max-md:max-w-full">
            <div className="flex flex-col justify-center w-full max-md:max-w-full">
              <div className="flex flex-col justify-center pb-2.5 w-full text-base text-right min-h-[55px] text-slate-800 max-md:max-w-full">
                <div className="flex flex-wrap justify-center items-center px-1.5 w-full min-h-[45px] max-md:max-w-full">
                  <div className="flex flex-col flex-1 shrink self-stretch px-3 pt-3 pb-3.5 my-auto w-full bg-white rounded-sm border-b border-solid basis-0 border-b-yellow-500 max-w-[890px] min-h-[40px] min-w-[240px] max-md:max-w-full">
                    <label htmlFor="fullName" className="sr-only">
                      שם מלא
                    </label>
                    <input
                      type="text"
                      id="fullName"
                      name="fullName"
                      className="w-full bg-transparent"
                      placeholder="שם מלא *"
                      required
                      aria-label="שם מלא"
                    />
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center pb-2.5 w-full text-base text-right min-h-[55px] text-slate-800 max-md:max-w-full">
                <div className="flex flex-wrap justify-center items-center px-1.5 w-full min-h-[45px] max-md:max-w-full">
                  <div className="flex flex-col flex-1 shrink self-stretch px-3 pt-3 pb-3.5 my-auto w-full bg-white rounded-sm border-b border-solid basis-0 border-b-yellow-500 max-w-[890px] min-h-[40px] min-w-[240px] max-md:max-w-full">
                    <label htmlFor="phone" className="sr-only">
                      טלפון
                    </label>
                    <input
                      type="tel"
                      id="phone"
                      name="phone"
                      className="w-full bg-transparent"
                      placeholder="טלפון *"
                      required
                      aria-label="טלפון"
                    />
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center pb-2.5 w-full text-base text-right min-h-[55px] text-slate-800 max-md:max-w-full">
                <div className="flex flex-wrap justify-center items-center px-1.5 w-full min-h-[45px] max-md:max-w-full">
                  <div className="flex flex-col flex-1 shrink self-stretch px-3 pt-3 pb-3.5 my-auto w-full bg-white rounded-sm border-b border-solid basis-0 border-b-yellow-500 max-w-[890px] min-h-[40px] min-w-[240px] max-md:max-w-full">
                    <label htmlFor="email" className="sr-only">
                      כתובת מייל
                    </label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      className="w-full bg-transparent"
                      placeholder="כתובת מייל *"
                      required
                      aria-label="כתובת מייל"
                    />
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center pb-2.5 w-full min-h-[50px] max-md:max-w-full">
                <div className="flex flex-wrap justify-center items-center px-1.5 w-full min-h-[40px] max-md:max-w-full">
                  <div className="flex relative flex-1 shrink justify-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full">
                    <label htmlFor="message" className="sr-only">
                      על מה נדבר?
                    </label>
                    <textarea
                      id="message"
                      name="message"
                      className="flex z-0 flex-col flex-1 shrink justify-center pt-1.5 pr-3.5 pb-2 pl-5 text-base leading-loose text-right bg-white rounded border-b border-solid basis-0 border-b-yellow-500 max-w-[880px] min-h-[40px] min-w-[240px] text-slate-800 max-md:max-w-full"
                      placeholder="על מה נדבר?"
                      aria-label="על מה נדבר?"
                    ></textarea>
                    <div className="flex absolute top-1.5 left-2.5 z-0 flex-col items-end self-start pt-1.5 pb-3 bottom-[7px] min-h-[26px] w-[11px]">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/0c4bd9fb7fce4d71f596cbe7566a81b85ec84b31c02f7bb1ea4d992482ffedd5?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856"
                        className="object-contain aspect-square w-[11px]"
                        alt=""
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center pb-2.5 w-full text-base font-medium leading-none text-center text-white min-h-[50px] max-md:max-w-full">
                <div className="flex flex-wrap items-end pl-1 w-full min-h-[40px] pr-[738px] max-md:pr-5 max-md:max-w-full">
                  <button
                    type="submit"
                    className="flex flex-col grow shrink justify-center px-6 py-3.5 bg-yellow-500 rounded min-h-[40px] w-[118px] max-md:px-5"
                  >
                    <div className="flex justify-center items-center pr-1.5 w-full">
                      <span className="self-stretch my-auto">
                        צור פניה חדשה
                      </span>
                    </div>
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </section>
  );
};

export default ContactForm;
