/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroSection: React.FC = () => {
  return (
    <section className="flex z-0 flex-col pt-2.5 w-full min-h-[1200px] max-md:max-w-full">
      <div className="flex flex-col flex-1 items-center w-full max-md:max-w-full">
        <div className="flex justify-center w-full max-w-[1920px] max-md:max-w-full">
          <div className="flex flex-col flex-1 shrink w-full basis-0 min-w-[240px] max-md:max-w-full">
            <div className="flex flex-col items-end w-full max-md:max-w-full">
              <div className="flex flex-col pt-36 w-full text-5xl text-center bg-slate-800 max-md:pt-24 max-md:text-4xl">
                <div className="flex flex-col p-2.5 w-full max-md:max-w-full max-md:text-4xl">
                  <div className="flex flex-col justify-center w-full text-xs leading-6 text-gray-200 max-w-[1907px] max-md:max-w-full">
                    <div className="flex flex-col flex-1 w-full max-md:max-w-full">
                      <div className="w-full px-[894px] max-md:px-5 max-md:max-w-full">
                        דף הבית/הדרך שלנו
                      </div>
                    </div>
                  </div>
                  <h1 className="flex flex-col justify-center mt-5 w-full font-bold leading-none text-yellow-500 max-w-[1907px] max-md:max-w-full max-md:text-4xl">
                    <div className="flex flex-col flex-1 w-full max-md:max-w-full max-md:text-4xl">
                      <div className="w-full pl-[845px] pr-[846px] max-md:px-5 max-md:max-w-full max-md:text-4xl">
                        החזון שלי
                      </div>
                    </div>
                  </h1>
                  <p className="flex flex-col justify-center mt-5 w-full leading-tight text-white max-w-[1907px] max-md:max-w-full max-md:text-4xl">
                    <div className="flex flex-col flex-1 justify-center items-center px-20 py-2.5 w-full max-md:px-5 max-md:max-w-full max-md:text-4xl">
                      <div className="flex flex-col max-w-full w-[978px] max-md:text-4xl">
                        <div className="self-start ml-48 max-md:ml-2.5 max-md:text-4xl">
                          {" "}
                          בגוגל.
                        </div>
                        <div className="mt-6 max-md:max-w-full max-md:text-4xl">
                          אך אנחנו לא מבטיחים הבטחות אלא נותנים תוצאות.
                        </div>
                      </div>
                    </div>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
