/**
 * This code was generated by Builder.io.
 */
import React from "react";

const WebServiceSection: React.FC = () => {
  return (
    <div className="flex flex-col md:flex-nowrap grow-0 shrink self-auto justify-normal items-normal w-full bg-slate-800 min-h-[260px] px-[10px] max-md:max-w-full">
      <div className="flex flex-wrap md:flex-initial flex-1 py-2.5 size-full content-[1366px]">
        <div
          className={`flex flex-col gap-5 grow-0 box-border shrink p-2.5 text-right md:w-[57.975%] w-full max-md:max-w-full`}
        >
          <div
            className={` text-4xl font-bold max-w-full leading-10 text-sky-400 max-md:max-w-full`}
          >
            <div className="h-full max-md:max-w-full">
              <h2 className="font-rubik font-bold text-[40px] leading-[48px] max-md:px-5 max-md:max-w-full">
                חודש 1-2: פיתוח ובניית אתרים
              </h2>
            </div>
          </div>
          <div className="w-full text-xl text-white font-rubik text-[20px] leading-[25px] font-normal max-md:max-w-full">
            <div className="w-full max-md:max-w-full">
              <ul
                className="my-[20px] list-disc w-full max-md:pr-5 max-md:max-w-full"
                style={{ padding: "revert", margin: "revert" }}
              >
                <li className="w-full leading-6 max-md:max-w-full">
                  בדיקת שביעות רצון: בסיום שלב זה נוודא שהאתר תואם את הציפיות
                  שלך ושאתה מרוצה מהתוצאה. אנו נבצע שינויים ועדכונים לפי הצורך
                  כדי להבטיח שהאתר עומד בסטנדרטים שלך.
                </li>
                <li className="w-full leading-6 max-md:max-w-full">
                  בנה את האתר שלך: במהלך החודש הראשון והשני נבנה את האתר שלך
                  ביחד. המטרה היא ליצור אתר אינטרנט מעוצב ומהיר המותאם לצרכים
                  הייחודיים של העסק שלך. זה כולל עיצוב מותאם אישית, תוכן ראשוני
                  ואופטימיזציה בסיסית למנועי חיפוש (SEO).
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="flex flex-col grow-0 gap-[20px] shrink-0 justify-center border-solid border-r-[3px] border-r-sky-500 self-start md:w-[18.766%] w-full">
          <div
            className={`flex flex-col pt-2.5 pr-3.5 pb-12 pl-2.5 w-full min-h-[254px]`}
          >
            <div className="w-full max-w-[256px]">
              <div className="w-full">
                <div className="flex flex-col items-center pr-6 pb-2 pl-6 w-full max-md:px-5">
                  <div className="flex items-start max-w-full w-[186px]">
                    {/* <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/46ada65a9fa2fc8ddb662510a6ed396e10ce559d20d14567a58486fec71b7582?placeholderIfAbsent=true&apiKey=addd44d0d4a74bbf9dcbe1a996be8856"
                      className="object-contain aspect-square w-[186px]"
                      alt="Service illustration"
                    /> */}
                    <svg
                      width="187"
                      height="166"
                      viewBox="0 0 187 166"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M150.223 0.523315H36.5565C35.2649 0.523315 34.0378 1.16915 33.3274 2.26707L1.03571 49.8004C0.099247 51.2212 0.196122 53.0942 1.26175 54.3858L90.3867 164.436C91.9367 166.341 94.843 166.341 96.393 164.436L185.518 54.3858C186.584 53.0619 186.68 51.2212 185.744 49.8004L153.485 2.26707C152.742 1.16915 151.547 0.523315 150.223 0.523315ZM143.991 16.0233L164.432 47.0233H142.344L125.649 16.0233H143.991ZM78.7295 16.0233H108.018L124.713 47.0233H62.067L78.7295 16.0233ZM42.7888 16.0233H61.1305L44.4357 47.0233H22.3482L42.7888 16.0233ZM28.9034 62.5233H45.5013L67.5565 114.19L28.9034 62.5233ZM62.1315 62.5233H124.648L93.3899 141.089L62.1315 62.5233ZM119.223 114.19L141.246 62.5233H157.844L119.223 114.19Z"
                        fill="#3AB2E4"
                      />
                    </svg>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default WebServiceSection;
