/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavigationItem from "./NavigationItem";

const navigationItems = [
  "צרו קשר",
  "הדרך שלנו",
  "תיק עבודות",
  "אודותינו",
  "דף הבית",
];

const NavigationMenu: React.FC = () => (
  <div className="flex flex-col justify-center self-stretch my-auto text-base font-bold leading-none text-right text-yellow-500 max-md:mt-10 max-md:max-w-full">
    <div className="flex flex-col flex-1 w-full max-md:max-w-full">
      <div className="flex justify-center w-full max-md:max-w-full">
        <div className="flex flex-wrap justify-center h-full min-w-[240px] max-md:max-w-full">
          {navigationItems.map((item, index) => (
            <NavigationItem key={index} label={item} />
          ))}
        </div>
      </div>
    </div>
  </div>
);

export default NavigationMenu;
